name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: https://soundcloud.com/user-606474189/bunx-n-traffic_cdawg_fm_belize-dec28th2019
        echo Add other actions to build,
        echo test, and deploy your project.
